Repository nephio-project/kpt-backstage-plugins, pull requests merged in 2023-05, with the labels that each got.

#2 Create .prow.yaml
  .prow.yaml
Labels: ok-to-test, lgtm, approved

#4 Add Nephio images
  images/nephio-background.png
  images/nephio_logo_colorwhite_horizontal.svg
Labels: lgtm, approved

#5 Update ci to run type script compiler and prettier
  .prow.yaml
Labels: ok-to-test, lgtm, approved

#6 Move the images to the right place
  packages/app/public/nephio-background.png
  packages/app/public/nephio_logo_colorwhite_horizontal.svg
Labels: approved

#3 Viewer for PV and PVS
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/kptfile.ts
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/packageVariant.ts
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/packageVariantSet.ts
  plugins/cad/src/types/PackageVariant.ts
  plugins/cad/src/types/PackageVariantSet.ts
Labels: lgtm, approved

#7 Sync upstream changes
  plugins/cad-backend/README.md
  plugins/cad-backend/src/service/config.ts
  plugins/cad-backend/src/service/router.ts
  plugins/cad/config.d.ts
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/default.ts
Labels: lgtm, approved

#9 Sync upstream changes
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/StructuredMetadata.tsx
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/default.ts
  plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/secret.ts
  plugins/cad/src/types/Secret.ts
Labels: lgtm, approved

#10 Update ci to fail immediately if any command has a non-zero exit code
  .prow.yaml
Labels: lgtm, approved
